solidity/python/Formula/Power/__init__.py

1. Replace the constant value with a PRECISION-dependent (constant) variable.
2. Replace the bit-wise assertion (which was BTW wrong due to operator precedence) with a simpler inequality assertion.

Fix the max-value assertion.

---

solidity/python/Formula/Power/__init__.py

Make sure that the product is less than 256-bit long.

Add an assertion to safeMul

---

solidity/contracts/BancorFormula.sol

This change was originally made at https://github.com/bancorprotocol/contracts/commit/353c94803ab6411b5cb1d57a4b1df8a877373617 and reverted at https://github.com/bancorprotocol/contracts/commit/2961405e717378fc754add165e3a6d326825754f.

Remove precision-loss guards

---

solidity/contracts/BancorFormula.sol

If base <= ~20, then the upper bound of ln(base) is 3.
So the case of returning 3 can be extended from base <= 8 to base <= ~20.
This improves:
- The accuracy for 16 <= base <= ~20, which in the old version returned 4 instead of 3.
- The performance for 9 <= base <= ~20, which in the old version were calculated via floorLog2.

Improve accuracy and performance

---

solidity/python/Formula/Power/__init__.py

Copy-paste the code from solidity into python, and change only what must be changed (i.e., language syntax) in order for it to run.

Align python emulation with solidity contract

---

solidity/python/constants/PrintMaxExpPerPrecision.py

The maximum value that we can use when calling function fixedExpUnsafe depends on precision.
For our minimum precision of 32, it is 0x386bfdba29.
For each additional bit, it increases by approximately 1.9.
Our precision may be a value between 32 and 64, in multiples of 2 (i.e., 32, 34, 36, ..., 64).
So in order to calculate the maximum value that we can use when calling function fixedExpUnsafe, we start from 0x386bfdba29 and multiply it by 1.9^2 an appropriate amount of times, i.e., "(precision-32)/2" times.
Since we cannot use non-integers, we should multiply by 19^2 and divide by 10^2.
But there is a better approximation, since this "1.9" factor in fact extends beyond one decimal digit.
In order to find the best factor, added in this commit is a binary search for all possible precision …

Calculate the max factor for increasing MaxExp by

---

solidity/python/Formula/Power/__init__.py

Update the python emulation according to the solidity contract.
This update is mostly documentation.
There is one change in the code, of the multiplication factor used in function fixedExp (from 367765941410054209 to 367765941410234761).

Update python according to solidity

---

solidity/python/Formula/Power/__init__.py

And make this function slightly more readable (using a simple binary-search).
This change aligns the python emulation with the solidity contract.

Reduce the average running time of floorLog2

---

solidity/contracts/BancorFormula.sol

Use ">=" (GTE) instead of "if/else" (JUMPI).
According to https://docs.google.com/spreadsheets/d/1m89CVujrQe5LAFJ8-YAUCcNK950dUzMQPMJBxRtGCqs/edit#gid=0, it should be more efficient.

Optimize floorLog2

---

solidity/contracts/BancorFormula.sol

Use a larger base when computing the maximum factor with which we calculate the maximum value permitted for function fixedExpUnsafe.
So instead of the arbitrary base of 10^17, we use a base of 2^62, which gives the highest possible accuracy in computing the max-exp-per-precision.

Minor accuracy improvement

---

solidity/contracts/BancorFormula.sol

Instead of returning Floor(Log2(base)), return Ceiling(Ceiling(Log2(base))*LogE(2))).

Improve the natural log upper bound estimation

---

solidity/contracts/BancorFormula.sol

Avoid truncation by returning uint256 instead of uint8 in functions lnUpperBound and floorLog2.

Fix possible truncation of intermediate results

---

solidity/contracts/BancorFormula.sol

Add 32-bit accuracy to the output of 'lnUpperBound' (which should now be renamed to something like 'lnUpperBoundFixed32'.
This improves accuracy only when the input of 'lnUpperBound' is larger than e^3 (~20).

Improve precision prediction

---

solidity/contracts/BancorFormula.sol

1. Improve the accuracy of testing whether the input is smaller than e^1, e^2, e^3 or neither.
2. Add and use function ceilLog2 (this is essentially just for coding clarification).

Update function lnUpperBound32

---

solidity/contracts/BancorFormula.sol

1. Remove the assertion of denominator < MAX_VAL:
If denominator <= numerator and numerator < MAX_VAL, then obviously denominator < MAX_VAL.
2. Remove the assertion of numerator != 0:
If denominator <= numerator and denominator != 0, then obviously numerator != 0.
3. Merge the remaining asserts into a single line which depicts the range of the input:
0 < denominator <= numerator < 2 ^ (256 - _precision).
4. Update the documentation accordingly.

Remove redundant asserts and update documentation

---

solidity/python/CoverageSale.py

1. Make it clear that we run each test-case of amount <= supply (instead of using the 'continue' statement on the opposite expression).
2. Print consecutively (makes it a little slower, but also makes the printouts coming at a constant rate).

Prettify the Sale coverage test

---

solidity/python/CoveragePurchase.py

1. Print only when needed (otherwise the test is much slower)
2. Skip all cases of amount > reserve

Fix the Purchase coverage test

---

solidity/contracts/BancorFormula.sol

Changes:
1. Use a (global) array which maps every precision between 32 and 95 to the maximum exponent permitted.
2. Initialize this array at construction.
3. Binary-search this array when estimating the highest precision which can be used on the given input.
4. Use this array in order to assert that the exponent is not larger than the maximum permitted before calculating the Taylor series.
In this fix, instead of dynamically approximating the maximum exponent permitted for each precision (by starting from MAX_EXP_32 and multiplying by approximately 1.9 for every precision unit), we initialize an array containing the exact values of the maximum exponent permitted for each precision.
This (also) allows us to use binary-search instead of sequential search.
And we can therefore allow …

Improve accuracy

---

solidity/test/BancorFormula.js

Instead of verifying the limit of fixedExp, since the latter essentially verifies nothing but an assertion.
We want to verify that the limit set for fixedExpUnsafe is indeed the maximum limit.

Verify the limit of fixedExpUnsafe

---

solidity/test/BancorFormula.js

he auto-generated arrays contain info for precision 0 - 127, but the contract can only handle precision 32 - 127.

Start the precision loop from 32 and not from 0

---

.gitattributes

This helps make browsing code on GitHub much more pleasant. (More info [here](https://medium.com/@danielque/psa-how-to-fix-githubs-syntax-highlighting-for-solidity-4e9867c540b6).)

Configure Solidity syntax highlighting

---

solidity/test/BancorNetwork.js

trusted/untrusted private keys are no longer hardcoded into the tests (So ganache will work with any mnemonic), and have been replaces with accounts[3] and accounts[1] (addresses) respectively.

Test mnemonic fix

---

solidity/contracts/converter/BancorConverter.sol
solidity/contracts/converter/BancorConverterUpgrader.sol
solidity/test/BancorConverterUpgrader.js
solidity/test/BancorNetwork.js

quickBuyPath along with all its helper functions have been removed from the newest converter version (0.11), the BancorConverterUpgrader has also been updated to reflect these changes, and all the tests have been updated to not use/test the quickBuyPath

quickBuyPath removed from contracts and tests

---

scripts/fix-modules.js

Make sure that this script is not executed more than once (i.e., as a result of any additional call to `npm install`).

Improve fix-modules.js

---

solidity/contracts/converter/types/liquidity-pool-v2/LiquidityPoolV2Converter.sol
solidity/python/Utilities/V2Flow/engine/__init__.py

During the calculation of the amount to return upon liquidity-removal, we apply an exit-fee depending on the ratio between the primary token's staked balance and actual balance.
This yields a multiplication of 3 potentially-large values, which can lead to an overflow.
In order to reduce the probability of that, we multiply the returned amount by the exit-fee after calculating that amount (instead of incorporating that fee into the computation of that amount).

Function `removeLiquidityReturn` overflow protection

---

solidity/contracts/utility/ReentrancyGuard.sol

Change the type of a storage variable from `bool` to `uint256`, in order to reduce gas-cost by ~1600 (2 storage-read operations).

Reentrancy guard optimization

---

solidity/contracts/converter/ConverterBase.sol
solidity/contracts/converter/types/liquidity-pool-v1/LiquidityPoolV1Converter.sol

If the previous average rate was never calculated, the average rate is equal to the current rate.
Note that after a pool is liquidated completely, the previous average rate may return to a 'never calculated' state, but there is no problem with that.

Fix internal function `recentAverageRate`

---

solidity/contracts/liquidity-protection/LiquidityProtection.sol
solidity/test/LiquidityProtection.js
solidity/test/LiquidityProtectionEdgeCases.js

In the read-only functions `poolROI` and `removeLiquidityReturn`, avoid reverting when the maximum permitted deviation of the average rate from the spot rate is exceeded.

Skip average-rate validation in read-only functions

---

solidity/contracts/liquidity-protection/LiquidityProtection.sol

Remove a couple of `internal` functions that are used only once (put their code where each one of them is called from).
We previous used these functions in order to reduce code-size, when we had a few others of similar nature.
But now that this is no longer the case, we may as well remove the "extra text" (and in addition to that, the `onlyOwner` modifier being applied on internal functions is generally bad practice; it was done so in order to reduce the code-size, but it is no longer useful for this purpose at this point).

Code Cleanup

---

solidity/contracts/converter/ConverterUpgrader.sol

Upon upgrading a converter, withdraw the ether or tokens of each reserve only if the balance of the converter in that reserve is larger than zero.

Upgrader Converter Upgrader

---

solidity/contracts/liquidity-protection/LiquidityProtection.sol
solidity/contracts/liquidity-protection/LiquidityProtectionSettings.sol
solidity/contracts/liquidity-protection/interfaces/ILiquidityProtectionSettings.sol
solidity/test/LiquidityProtection.js
solidity/test/LiquidityProtectionAverageRate.js
solidity/test/LiquidityProtectionEdgeCases.js
solidity/test/LiquidityProtectionSettings.js
solidity/test/helpers/Constants.js
solidity/utils/test_deployment.js

1. Remove the 'MintedNetworkToken' functionality from `LiquidityProtectionSettings`.
2. Remove the 'migrateData' function from `LiquidityProtection`.

LP contracts Cleanup

---

solidity/utils/test_deployment.js

Since we have 2 overloaded versions of function `addLiquidity` in contract `StandardPoolConverter`, call the desired one explicitly.

Fix call to function `addLiquidity` in contract `StandardPoolConverter`

---

solidity/contracts/bancorx/BancorX.sol
solidity/contracts/converter/ConverterBase.sol
solidity/contracts/converter/types/standard-pool/StandardPoolConverter.sol
solidity/contracts/liquidity-protection/LiquidityProtectionSettings.sol
solidity/contracts/liquidity-protection/LiquidityProtectionStore.sol
solidity/contracts/token/DSToken.sol
solidity/contracts/utility/TokenHolder.sol
solidity/contracts/utility/Utils.sol
solidity/test/Converter.js
solidity/test/DSToken.js
solidity/test/LiquidityProtectionSettings.js
solidity/test/TokenHolder.js

In this PR, I have consolidated `validAddress` and `notThis` into the existing `validExternalAddress` modifiers. 
Please note, that in some of the cases I've removed `notThis` and kept only `validAddess` (e.g., when the wrong address can be changed back, when removing a previously verified address, etc.)

Remove/consolidate `notThis` modifiers

---

solidity/contracts/converter/types/standard-pool/StandardPoolConverter.sol

Following the removal of function `baseReserveBalance`, unify the common code in function `baseReserveBalances` and function `processNetworkFees` into a dedicated function.

Common utility function `networkWalletAndFees`

---

solidity/contracts/helpers/TestLiquidityProtection.sol
solidity/contracts/liquidity-protection/LiquidityProtection.sol
solidity/test/LiquidityProtection.js
solidity/test/LiquidityProtectionAverageRate.js
solidity/test/LiquidityProtectionEdgeCases.js
solidity/test/LiquidityProtectionStateless.js
solidity/utils/test_deployment.js

1. Update `LiquidityProtection` and `TestLiquidityProtection` syles according to the new style.
2. Add required getters
3. Remove the obsoleted `updatingLiquidityOnly` mechanism
4. Remove the unused `baseTokenAvailableSpace` and `networkTokenAvailableSpace` functions
5. Restore explicit constructor
6. Remove unneeded caching of immutable state variables
7. Update and refactor the tests accordingly

Refactor LiquidityProtection

---

solidity/contracts/liquidity-protection/LiquidityProtection.sol
solidity/test/LiquidityProtection.js

In function `addProtectedLiquidity`, verify the deviation of the current spot rate from the recent average rate.

Verify rate deviation when adding protected liquidity

---

solidity/contracts/helpers/TestCall.sol
solidity/contracts/liquidity-protection/LiquidityProtection.sol
solidity/test/LiquidityProtection.js

This PR adds the `transferPositionAndCall` function, allowing the caller to specify a custom transfer position notification callback.

Allow transferring position with an optional external notification callback

---

package.json

Move the contract dependencies from `devDependencies` to `dependencies`, in order to support compiling the contracts in other repositories.

Fix Dependencies
