bancorprotocol/contracts-solidity

solidity/.gitignore, solidity/hypothesis/test.py
(These all fail - edge cases? You tell me.)
=> Added hypothesis tests

solidity/contracts/BancorFormula.sol, solidity/hypothesis/test.py
Fix a false positive generated by hypothesis.
=> Updated the hypothesis to be more accurate

solidity/contracts/BancorFormula.sol
1. In function calculatePurchaseReturn:
- Change '/ resD' to '>> PRECISION'
- Change '/ 0x100000000' to '>> PRECISION'
2. In function calculateSaleReturn:
- Change '/ 0x100000000' to '>> PRECISION'
3. In function fixedLog2:
- Get rid of the 'lo' variable and all related operations, since the input is necessarily larger than or equal to "fixedOne", which yields 'lo = 0'
=> Pretty cosmetic

solidity/python/FormulaTest.py
Add worst sale-accuracy and worst purchase-accuracy measurement.
=> Add worst accuracy measurement

solidity/python/Formula/__init__.py
Align this with the actual contract (solidity) code.
=> Remove precision-loss guards

solidity/contracts/BancorFormula.sol
Change the PRECISION constant to a dynamic value, passed to the 'power' function (and all other functions in the calling tree).
Method:
- Given base and exponent, we need to calculate base^exponent.
- Instead, we calculate e^(ln(base)*exponent).
- The value of ln(base) is represented with an integer slightly smaller than ln(base)*2^PRECISION.
- The larger PRECISION is, the more accurately this value represents the real value.
- However, function fixedExpUnsafe(x), which calculates e^x, is limited to a maximum value of x.
- The limit depends PRECISION (e.g, for PRECISION=32, the maximum value of x is 0x386bfdba29).
- Hence before calling the 'power' function, we need to estimate an upper-bound for ln(base)*exponent.
- Dividing 0x386bfdba29 by this value will tell us what value we can set …
=> Dynamic Precision

solidity/python/Formula/__init__.py
Set the python script as close as possible to the solidity contract
=> Update script according to contract

solidity/python/Formula/Power/__init__.py
Update the python emulation according to the solidity contract.
=> Update python according to solidity

solidity/python/Formula/__init__.py
Update the python emulation according to the solidity contract (this is essentially a cosmetic commit, since only the documentation has slightly changed).
=> Update python code according to solidity code.

solidity/python/constants/PrintMaxExpPerPrecision.py
Since we are now using it more than once.
=> Implement a generic binary-search function

solidity/contracts/BancorFormula.sol
And make it slightly more readable (a simple binary-search).
=> Reduce the average running time of floorLog2

solidity/contracts/BancorFormula.sol
Cast Boolean expression to uint8 before applying arithmetic operation.
=> Fix a compilation error

solidity/python/CoveragePurchase.py
Instead of testing only cases of amount <= reserve, test all cases of amount <= reserve OR amount <= supply.
=> Expand the Purchase coverage test

solidity/python/CoverageSale.py
Otherwise the test is much slower
=> Print only when needed

solidity/contracts/BancorFormula.sol
Operator precedence issue (>= vs <<).
=> Potential bug-fix

solidity/contracts/BancorFormula.sol
The highest approximation of ln(2) which can be used safely is 0x2c5c85fdf473de6af278ece600fcbda / 2 ^ 122.
We were using 0xb17217f7d1cf78 / 2 ^ 56 just because Python's accuracy for ln(2) cannot surpass this value.
Since python accuracy is insufficient, we compute this value via https://www.wolframalpha.com/input/?i=convert+(floor(log(2)*2%5E122))+to+hex.
=> Improve the accuracy of the 'ln' function

solidity/contracts/BancorFormula.sol
Will later add a script that auto-generates them.
=> Define pre-calculated constants as global

solidity/contracts/ContractIds.sol, solidity/contracts/converter/BancorConverter.sol, solidity/contracts/utility/ContractRegistry.sol, solidity/test/BancorConverter.js, solidity/test/ContractRegistry.js
The ContractRegistry now also registers the address of the current ContractRegistry, initialised to point to itself
=> Update registry function

scripts/fix-modules.js
fix-modules script protected with try/catch
=> Fix modules fix

solidity/python/FormulaSolidityPort/__init__.py
Fix the documentation of function `optimalExp` in contract `BancorFormula`.
=> Fix documentation

package-lock.json, package.json, solidity/contracts/bancorx/BancorX.sol, solidity/contracts/converter/BancorConverter.sol, solidity/contracts/converter/interfaces/IBancorConverter.sol, solidity/contracts/token/SmartTokenController.sol, solidity/contracts/token/interfaces/ISmartTokenController.sol, solidity/test/BancorConverter.js, solidity/test/BancorConverterUpgrader.js, solidity/test/BancorNetwork.js, solidity/test/BancorNetworkWithOldConverter.js, solidity/test/BancorX.js, solidity/test/SmartTokenController.js, solidity/test/XConversions.js
Reverts bancorprotocol/contracts#298
=> Revert "Bancorx generic erc20 support"

package-lock.json, package.json, solidity/contracts/bancorx/BancorX.sol, solidity/contracts/converter/BancorConverter.sol, solidity/contracts/converter/interfaces/IBancorConverter.sol, solidity/contracts/token/SmartTokenController.sol, solidity/contracts/token/interfaces/ISmartTokenController.sol, solidity/test/BancorConverter.js, solidity/test/BancorConverterUpgrader.js, solidity/test/BancorNetwork.js, solidity/test/BancorNetworkWithOldConverter.js, solidity/test/BancorX.js, solidity/test/SmartTokenController.js, solidity/test/XConversions.js
Reverts bancorprotocol/contracts#299
=> Revert "Revert "Bancorx generic erc20 support""

solidity/contracts/converter/BancorConverter.sol
BancorConverter functions:
- `fund`
- `liquidate`
- `addLiquidity`
- `removeLiquidity`
=> Fix balance-handling in liquidity functions

solidity/contracts/converter/BancorConverter.sol
1. When purchasing at supply = 0, return the reserve amount without fee.
2. When selling the entire supply, return the entire reserve without fee.
=> Zero Supply Liquid Token

solidity/contracts/converter/types/liquidity-pool-v2/LiquidityPoolV2Converter.sol, solidity/test/LiquidityPoolV2Converter.js
Change function `removeLiquidityReturn` to `removeLiquidityAmountAndFee`, which returns on top of the amount after the fee, also the fee.
=> removeLiquidityAmountAndFee

solidity/contracts/liquidity-protection/LiquidityProtection.sol
This change is essentially cosmetic.
In function `removeLiquidity`, instead of calling `recentAverageRate` directly, we call `reserveTokenRate` (which then calls `recentAverageRate`).
=> Use `reserveTokenRate` in `removeLiquidity`

solidity/contracts/helpers/TestLiquidityProtection.sol, solidity/contracts/liquidity-protection/LiquidityProtection.sol, solidity/test/LiquidityProtection.js, solidity/test/LiquidityProtectionEdgeCases.js, solidity/test/LiquidityProtectionTokenRate.js
Restrict the average rate by an owner-configurable deviation from the actual rate.
=> Average rate max deviation

solidity/contracts/converter/types/standard-pool/StandardPoolConverter.sol
Create common code for bit-wise manipulation (increases the cost up to 700 gas units).
=> Bitwise Functionality

solidity/test/ConverterLiquidity.js
I've added a missing test case from the previous PR
=> Refactor to MAX_UINT256

solidity/contracts/liquidity-protection/LiquidityProtection.sol
Reduce the probability of arithmetic overflow in function `compensationAmount`.
=> Fix function `compensationAmount`

solidity/contracts/liquidity-protection/LiquidityProtection.sol, solidity/test/LiquidityProtection.js
Implement function `getNetworkCompensation` to be used in both `removeLiquidity` and `removeLiquidityReturn`.
=> Code Reuse

solidity/contracts/liquidity-protection/LiquidityProtection.sol
Reduce the number of times that the `networkToken` state-variable is read during each flow.
=> Optimize network token readings

solidity/utils/README.md, solidity/utils/test_deployment.js
1. Update utils/README.md.
2. Cosmetic fix in utils/test_deployment.js, in order to avoid confusion with the `liquidityProtectionParams` configuration object.
=> Minor fixes in utils

solidity/utils/stats_migration.js, solidity/utils/stats_verification.js
1. Add stats_verification.js.
2. In stats_migration.js, increase some of the write batch sizes.
=> Extend migration infrastructure

solidity/contracts/liquidity-protection/LiquidityProtectionStats.sol, solidity/contracts/liquidity-protection/interfaces/ILiquidityProtectionStats.sol, solidity/test/LiquidityProtectionStats.js, solidity/utils/stats_conclusion.js, solidity/utils/stats_migration.js, solidity/utils/stats_verification.js
1. Move role-renouncing to a separate script.
2. Change the `totalProviderAmount` table from `poolToken, reserveToken, provider` to `provider, poolToken, reserveToken`.
=> Fix total provider amounts

solidity/utils/test_deployment.js
1. Retry executing a transaction automatically upon any standard error
=> Improve the deployment script

solidity/utils/test_deployment.js
1. Fix the deployment script.
2. Extend the deployment script to deploy the staking-rewards module.
=> Fix and extend the deployment script

solidity/utils/test_deployment.js
Transfer the ownership of the network token contract to the network token governance contract.
=> Fix Deployment Script on 0.6.39

test/helpers/runDeployment.js
Transfer the ownership of the network token contract to the network token governance contract.
=> Fix Deployment Script
